stages: # List of stages for jobs, and their order of execution
  - lint
  - test

variables:
  URL: "https://example.cypress.io"

lint:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  stage: lint
  before_script:
    - sudo npm i npx
  script:
    - npx eslint cypress

cypress:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
  stage: test
  before_script:
    - sudo npm i npx
  script:
    - npm i
    - npx cypress run